# Generated by Django 5.2.5 on 2025-09-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('investor', 'Investor'), ('farmer', 'Farmer')], default='investor', help_text='Determines user capabilities in the system.', max_length=20),
        ),
    ]
