# Generated by Django 5.2.5 on 2025-09-18 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_loginlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('funding_goal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('funds_raised', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('investors_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('fundraising', 'Fundraising'), ('growing', 'Growing'), ('harvest', 'Harvest Phase'), ('completed', 'Completed'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('image', models.CharField(blank=True, help_text='Optional emoji or image id for UI', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=True)),
                ('farmer', models.ForeignKey(limit_choices_to={'role': 'farmer'}, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
