# Generated by Django 5.2.5 on 2025-09-20 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_kycupload_projectupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='wallet_address',
            field=models.CharField(blank=True, help_text='Optional Hedera account id or wallet address', max_length=200, null=True),
        ),
    ]
