# Generated by Django 5.2.5 on 2025-09-22 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_walletnonce'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='wallet_public_key',
            field=models.TextField(blank=True, help_text='Optional Hedera public key (saved after verification)', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='farm_image'),
        ),
    ]
